### ISSUE TITLE
"Contact Us" does not work for non-VMware e-mail addresses.

### ISSUE THREAD

**Issue by tschwaller** [vmware/hatchway#3]
e-mails from non-VMware accounts to  [hatchway@vmware.com](mailto:hatchway@vmware.com) do get an error message (see screenshot). The e-mail address is menioned e.g. on the following pages:

https://vmware.github.io/hatchway/
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/contactus.html

<img width="533" alt="image" src="https://user-images.githubusercontent.com/6458940/41526646-240fcfce-72e5-11e8-8a34-1965f48145f5.png">

**Comment by tusharnt** [comment]
I am following up on this internally to get this resolved.

**Comment by tusharnt** [comment]
This has been fixed.
